### ISSUE TITLE
errors when building the OpenGL example

### ISSUE THREAD

**Issue by piotrklos-tcl** [cnr-isti-vclab/piccante#15]
I'm trying to build the **opengl_tone_mapping** example. I use Ubuntu 18.04, so I simply installed Qt with apt, opened the .pro file with QtCreator and clicked build.

I'm getting like 9000 warnings, as well as some errors. 
The first error:
```
In file included from ../../include/gl.hpp:38:0,
                 from ../../include/piccante.hpp:226,
                 from ../opengl_tone_mapping/main.cpp:42:
../../include/util/gl/program.hpp: In member function ‘bool pic::ProgramGL::checkShaderStatus()’:
../../include/util/gl/program.hpp:46:9: error: ‘glGetShaderiv’ was not declared in this scope
         glGetShaderiv(object, GL_COMPILE_STATUS, &bCheckStatus);
         ^~~~~~~~~~~~~
```
I was thinking that maybe OpenGL was not installed correctly, so I ran an OpenGL example from Qt itself (the /usr/lib/x86_64-linux-gnu/qt5/examples/opengl/2dpainting from qtbase5-examples package) and it works fine.

What could be the issue?

**Comment by banterle** [comment]
Have you tried the dev branch?

**Comment by piotrklos-tcl** [comment]
It's awesome that you are looking into this, thanks!

**Comment by banterle** [comment]
all examples should work now, please have a try to them.

**Comment by piotrklos-tcl** [comment]
OK, there's progress because **opengl_tone_mapping** is building without errors. :)

Unfortunately when I run it, I get a black image.

I tried to run a non-opengl example (**hdr_tone_mapping_simple**), to see if maybe OpenGL is still an issue. This, however results in some compile errors:

```
/home/pklos/od2019/hdr/piccante/examples/hdr_tone_mapping_simple/main.cpp:48: error: ‘JSONFile’ is not a member of ‘pic’
     pic::JSONFile tmp;
          ^~~~~~~~
```

**Comment by banterle** [comment]
> Unfortunately when I run it, I get a black image.
On my Ubuntu version, it works. It may be due to drivers
or graphics card. I tested it on a NVIDIA graphics card.

> I tried to run a non-opengl example (hdr_tone_mapping_simple), to see if maybe OpenGL is still an issue. This, however results in some compile errors:

I fixed hdr_tone_mapping_simple; it should work now.

**Comment by piotrklos-tcl** [comment]
> > Unfortunately when I run it, I get a black image.
> 
> On my Ubuntu version, it works. It may be due to drivers
> or graphics card. I tested it on a NVIDIA graphics card.

OK, it may be a display problem then. I'll try to save the image on the hard drive and see if it works.
 
> > I tried to run a non-opengl example (hdr_tone_mapping_simple), to see if maybe OpenGL is still an issue. This, however results in some compile errors:
> 
> I fixed hdr_tone_mapping_simple; it should work now.

That now works and I got some output, yay! Thanks a lot.

**Comment by banterle** [comment]
The problem here is that when you work with ImageGL you need to manually transfer the content from the GPU to the CPU. To do this, you need to call the function loadToMemory() before writing it.

**Comment by piotrklos-tcl** [comment]
OK, so after I've call loadToMemory(), the image is saved but it's a black one, like in the application. I'm almost out of ideas for now. Is there any test that I can do to tell if things are installed correctly?

**Comment by banterle** [comment]
It sounds like a problem with the device, what graphics do you have?

**Comment by piotrklos-tcl** [comment]
OK, I've run 
```
glxinfo | grep "OpenGL version"
```
and I've got
```
OpenGL version string: 3.0 Mesa 18.2.8
```
Is this too weak to run Piccante shaders?

This page http://vcg.isti.cnr.it/piccante/doc/html/index.html mentions "OpenGL 4.0 Core profile", although I'm a little confused about terminology here.

**Comment by banterle** [comment]
Piccante uses Core profile 4.0, and your adapter is version 3.0; so this may be the problem why it displays a blank image. I also never used Mesa, so I cannot give you help about it.

**Comment by piotrklos-tcl** [comment]
OK, good to know. I'll probably try it soon on another device. Thanks for all the help!

**Comment by banterle** [comment]
you are welcome, I close this issue since it is solved.
